@Api_Url = http://localhost:5257

GET {{Api_Url}}/weatherforecast/
Accept: application/json

###

POST {{Api_Url}}/Departments/Create 
Accept: application/json
Content-Type: application/json

{
  "name": ""
}