@Api_Url = http://localhost:5077

@Jwt_Key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkM2FmYWQxOC0yZTVjLTRjZmYtOTVkNi0wOGRjZGEyYzI5ZWIiLCJnaXZlbl9uYW1lIjoic2Vya2FuX3l1cnRAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJTZXJrYW4gWXVydCIsIm5iZiI6MTcyNjkxNjI0NSwiZXhwIjoxNzI3MTc1NDQ1LCJpYXQiOjE3MjY5MTYyNDUsImF1ZCI6IlRvZG9BcHAuY29tLnRyIn0.2SQzaVZJjbdSNp_Bo9JTElioiqkNhMTFRFM5ZjE4cAM

### SyncStationData
POST {{Api_Url}}/SyncDatas/SyncStationData
Accept: application/json
Content-Type: application/json

{
  "licenseNo": "123",
  "subLicenseNo": "12345",
  "tankGroups": 
  [
    {
      "name": "Diesel Tank1 Updated1",
      "tableUniqueId": "e2eb5da9-50c0-42ea-878c-2c268759a342"
    },
     {
      "name": "Diesel Tank2 Updated1",
      "tableUniqueId": "e2eb5da9-50c0-42ea-878c-2c268759a340"
    },
    {
      "name": "Tank Group Create1",
      "tableUniqueId": "e2eb5da9-50c0-42ea-878c-2c268759a343"
    },
    {
      "name": "Tank Group Create2",
      "tableUniqueId": "e2eb5da9-50c0-42ea-878c-2c268759a344"
    }
  ]
}