@Api_Url =  http://localhost:5077

@Jwt_Key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5MjE5MTY1Yi0yMmM0LTQzNWItNjBkOS0wOGRjYzc5MTkwYzUiLCJnaXZlbl9uYW1lIjoic2Vya2FuX3l1cnRAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJTZXJrYW4gWXVydCIsIm5iZiI6MTcyNTExNjA5OSwiZXhwIjoxNzI1Mzc1Mjk5LCJpYXQiOjE3MjUxMTYwOTksImF1ZCI6IlRvZG9BcHAuY29tLnRyIn0.lNNkarLoY5UCTdqNyV-jzaCRTYbjnAknT2EiWixlpmM

### Create
POST {{Api_Url}}/Departments/Create 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "name": "qwer"
}

### Update
PUT {{Api_Url}}/Departments/Update
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "a71c022a-c284-4465-5764-08dca43bf2e5",
  "name": "def"
}

### Delete
DELETE {{Api_Url}}/Departments/Delete
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "2acf96e9-945f-4606-c329-08dca49db6d1",
  "isDeleted": true 
}

### All
GET {{Api_Url}}/Departments/All
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

### Detail
GET {{Api_Url}}/Departments/Detail
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id":"2acf96e9-945f-4606-c329-08dca49db6d1"
}