@Api_Url =  http://localhost:5077

@Jwt_Key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJmYmJkNTc0Ni03YjM5LTQxZjktMzFhYy0wOGRkNzY5YWNiMmUiLCJnaXZlbl9uYW1lIjoic2Vya2FuX3l1cnRAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJTZXJrYW4gWXVydCIsIm5iZiI6MTc0NDExNjE5MSwiZXhwIjoxNzQ0Mzc1MzkxLCJpYXQiOjE3NDQxMTYxOTEsImF1ZCI6IlRvZG9BcHAuY29tLnRyIn0.U_XkNw34uwI9XGGW_4ZIw8jT8Kgd0QCi8ginaZUMTXA

### Create
POST {{Api_Url}}/Departments/Create 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "name": "Purchase"
}

### Update
PUT {{Api_Url}}/Departments/Update
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "06e03437-4eab-49c8-e3da-08dd78d3e24f",
  "name": "Purchase"
}

### Delete
DELETE {{Api_Url}}/Departments/Delete
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "06e03437-4eab-49c8-e3da-08dd78d3e24f",
  "isDeleted": true 
}

### All
GET {{Api_Url}}/Departments/All
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "filters": [],
  "pageRequest": {
    "currentPage": 1,
    "perPageCount": 10,
    "listAll": true
  }
}

### Detail
GET {{Api_Url}}/Departments/Detail
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id":"06e03437-4eab-49c8-e3da-08dd78d3e24f"
}