global using System;
global using System.Collections.Generic;
global using Arfware.ArfBlocks.Core;
global using Application.Configuration;
global using Infrastructure.RelationalDB;
global using Infrastructure.Services;
global using Arfware.ArfBlocks.Core.Extentions;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore;