@Api_Url = http://localhost:5077

@Jwt_Key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJmYmJkNTc0Ni03YjM5LTQxZjktMzFhYy0wOGRkNzY5YWNiMmUiLCJnaXZlbl9uYW1lIjoic2Vya2FuX3l1cnRAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJTZXJrYW4gWXVydCIsIm5iZiI6MTc0NDE4OTg0MywiZXhwIjoxNzQ0NDQ5MDQzLCJpYXQiOjE3NDQxODk4NDMsImF1ZCI6IlRvZG9BcHAuY29tLnRyIn0.PECpGmmWaRehuOzXm_a9ECiOXtxEI58u-W_B8vOX2es

### Create
POST {{Api_Url}}/TodoTasks/Create 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "title": "abc def",
  "description": "abc def description1",
  "assignedDepartmentId":"c741ae32-4cd1-4818-79be-08dd769b101e"
}

### Update
PUT {{Api_Url}}/TodoTasks/Update 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "bf268251-8dbb-4f4b-e642-08dca4a3121c",
  "title": "qwerty",
  "description": "abcdef desc",
  "assignedDepartmentId": "0f4f87cc-db80-4974-bae7-08dca0d9f40a"
}

### Delete
DELETE {{Api_Url}}/TodoTasks/Delete 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "bf268251-8dbb-4f4b-e642-08dca4a3121c",
  "isDeleted":true
}

### Complete
POST {{Api_Url}}/TodoTasks/Complete 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "74ff7e0a-2dd8-4bfa-d7d7-08dca40521df"
}

### Reject
POST {{Api_Url}}/TodoTasks/Reject 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "74ff7e0a-2dd8-4bfa-d7d7-08dca40521df"
}

### All
GET {{Api_Url}}/TodoTasks/All 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

### Detail
GET {{Api_Url}}/TodoTasks/Detail 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "719537da-66eb-43cd-d7d6-08dca40521df"
}

### MyTasks
GET {{Api_Url}}/TodoTasks/MyTasks 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

### Pendings
GET {{Api_Url}}/TodoTasks/Pendings 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}
