@Api_Url = http://localhost:5077

@Jwt_Key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJiNWFkZGE3OC1hMWVmLTQ0Y2UtZDg3NC0wOGRkNzhkNDNkZmQiLCJkZXBhcnRtZW50aWQiOiIwNmUwMzQzNy00ZWFiLTQ5YzgtZTNkYS0wOGRkNzhkM2UyNGYiLCJnaXZlbl9uYW1lIjoieWFoeWFfZXJhbHRheUBnbWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6IllhaHlhIEVyYWx0YXkiLCJuYmYiOjE3NDQ5NjM0NjUsImV4cCI6MTc0NTIyMjY2NSwiaWF0IjoxNzQ0OTYzNDY1LCJhdWQiOiJUb2RvQXBwLmNvbS50ciJ9.rEFroE2uAXzG1HHhdA9DnNj8U3qDRth-3El44iYXxgg

### Create
POST {{Api_Url}}/TodoTasks/Create 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "title": "deneme title",
  "description": "deneme desc",
  "assignedDepartmentId":"C741AE32-4CD1-4818-79BE-08DD769B101E"
}

### Update
PUT {{Api_Url}}/TodoTasks/Update 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "4E66D82A-148B-4DFE-2B3F-08DD78D5A24D",
  "title": "bug",
  "description": "bug fix",
  "assignedDepartmentId": "C741AE32-4CD1-4818-79BE-08DD769B101E"
}

### Delete
DELETE {{Api_Url}}/TodoTasks/Delete 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "4E66D82A-148B-4DFE-2B3F-08DD78D5A24D",
  "isDeleted":false
}

### Complete
POST {{Api_Url}}/TodoTasks/Complete 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "4E66D82A-148B-4DFE-2B3F-08DD78D5A24D",
  "actionComment": "testt"
}

### Reject
POST {{Api_Url}}/TodoTasks/Reject 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "4E66D82A-148B-4DFE-2B3F-08DD78D5A24D",
  "actionComment": "testt"
}

### All
GET {{Api_Url}}/TodoTasks/All 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "filters": [],
  "pageRequest": {
    "currentPage": 1,
    "perPageCount": 10,
    "listAll": true
  }
}

### Detail
GET {{Api_Url}}/TodoTasks/Detail 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "bc4a3f75-3154-4049-e307-08dd774681c4"
}

### MyTasks
GET {{Api_Url}}/TodoTasks/MyTasks
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "filters": [],
  "pageRequest": {
    "currentPage": 1,
    "perPageCount": 10,
    "listAll": true
  }
}

### Pendings
GET {{Api_Url}}/TodoTasks/Pendings 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

### Statistics
GET {{Api_Url}}/TodoTasks/Statistics 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

### UIDC
GET {{Api_Url}}/TodoTasks/UIDC 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "2BBD5E1E-FE3D-45C7-9E7F-BA0F2E798E1E"
}