@Api_Url = http://localhost:5077

@Jwt_Key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJmYmJkNTc0Ni03YjM5LTQxZjktMzFhYy0wOGRkNzY5YWNiMmUiLCJnaXZlbl9uYW1lIjoic2Vya2FuX3l1cnRAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJTZXJrYW4gWXVydCIsIm5iZiI6MTc0NDM2MTk4NywiZXhwIjoxNzQ0NjIxMTg3LCJpYXQiOjE3NDQzNjE5ODcsImF1ZCI6IlRvZG9BcHAuY29tLnRyIn0.reCt7syj-Nc3btEpwG9YF7E4NAUAV3zGdlJeQOeBMLA

### Create
POST {{Api_Url}}/TodoTasks/Create 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "title": "bug",
  "description": "bug fix",
  "assignedDepartmentId":"C741AE32-4CD1-4818-79BE-08DD769B101E"
}

### Update
PUT {{Api_Url}}/TodoTasks/Update 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "4E66D82A-148B-4DFE-2B3F-08DD78D5A24D",
  "title": "bug",
  "description": "bug fix",
  "assignedDepartmentId": "C741AE32-4CD1-4818-79BE-08DD769B101E"
}

### Delete
DELETE {{Api_Url}}/TodoTasks/Delete 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "4E66D82A-148B-4DFE-2B3F-08DD78D5A24D",
  "isDeleted":false
}

### Complete
POST {{Api_Url}}/TodoTasks/Complete 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "4E66D82A-148B-4DFE-2B3F-08DD78D5A24D"
}

### Reject
POST {{Api_Url}}/TodoTasks/Reject 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "4E66D82A-148B-4DFE-2B3F-08DD78D5A24D"
}

### All
GET {{Api_Url}}/TodoTasks/All 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "filters": [],
  "pageRequest": {
    "currentPage": 1,
    "perPageCount": 10,
    "listAll": true
  }
}

### Detail
GET {{Api_Url}}/TodoTasks/Detail 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "bc4a3f75-3154-4049-e307-08dd774681c4"
}

### MyTasks
GET {{Api_Url}}/TodoTasks/MyTasks
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "filters": [],
  "pageRequest": {
    "currentPage": 1,
    "perPageCount": 10,
    "listAll": true
  }
}

### Pendings
GET {{Api_Url}}/TodoTasks/Pendings 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}