@Api_Url = http://localhost:5077

@Jwt_Key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkYzhmMDAwMy1mMmU0LTQ5NWEtYjA1ZC0wOGRjYTAyMWM0NjEiLCJnaXZlbl9uYW1lIjoic2Vya2FuX3l1cnRAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJTZXJrYW4gWXVydCIsIm5iZiI6MTcyMDk3NzY5NiwiZXhwIjoxNzIxMjM2ODk2LCJpYXQiOjE3MjA5Nzc2OTYsImF1ZCI6IlRvZG9BcHAuY29tLnRyIn0.r8myYLcrPskDxylkBj_l9cbj4e8G3Js_8kMAOtBNQ1Y

### Create
POST {{Api_Url}}/TodoTasks/Create 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "title": "tesk task1",
  "description": "tesk task description1",
  "assignedDepartmentId":"0f4f87cc-db80-4974-bae7-08dca0d9f40a"
}

### Update
PUT {{Api_Url}}/TodoTasks/Update 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "719537da-66eb-43cd-d7d6-08dca40521df",
  "title": "abcdef",
  "description": "abcdef desc",
  "assignedDepartmentId": "0f4f87cc-db80-4974-bae7-08dca0d9f40a"
}

### Delete
DELETE {{Api_Url}}/TodoTasks/Delete 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "719537da-66eb-43cd-d7d6-08dca40521df",
  "isDeleted":true
}

//TODO: Hata veriyor
### Complete
PUT {{Api_Url}}/TodoTasks/Complete 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "74ff7e0a-2dd8-4bfa-d7d7-08dca40521df"
}

### Reject
POST {{Api_Url}}/TodoTasks/Reject 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "74ff7e0a-2dd8-4bfa-d7d7-08dca40521df"
}

### All
GET {{Api_Url}}/TodoTasks/All 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

### Detail
GET {{Api_Url}}/TodoTasks/Detail 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "719537da-66eb-43cd-d7d6-08dca40521df"
}

### MyTasks
GET {{Api_Url}}/TodoTasks/MyTasks 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

### Pendings
GET {{Api_Url}}/TodoTasks/Pendings 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}
