@Api_Url = http://localhost:5077

@Jwt_Key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhYWFlMTE3Yi1mZDQyLTQ4MTQtY2Q1My0wOGRjYTQyNjRlMzEiLCJnaXZlbl9uYW1lIjoieWFoeXlhQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoieWFoYXl5YSBFcmFsdGF5IiwibmJmIjoxNzIwOTc2Mzk5LCJleHAiOjE3MjEyMzU1OTksImlhdCI6MTcyMDk3NjM5OSwiYXVkIjoiVG9kb0FwcC5jb20udHIifQ.E2k5eNJffm-akUr2pYvfryAuS34QJkGyu0k9RioqRWs

### Login
POST {{Api_Url}}/Users/Login
Accept: application/json
Content-Type: application/json

{
  "email":"serkan_yurt@gmail.com"
}

### Create 
POST {{Api_Url}}/Users/Create 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "email": "yahyya@gmail.com",
  "firstName": "yahayya",
  "lastName": "Eraltay",
  "departmentId": "0f4f87cc-db80-4974-bae7-08dca0d9f40a"
}

### Update 
PUT {{Api_Url}}/Users/Update 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "16399264-cc9f-422a-f343-08dca403efbb",
  "email": "mery_glenn@gmail.com",
  "firstName": "Mery",
  "lastName": "Glenn",
  "departmentId": "0f4f87cc-db80-4974-bae7-08dca0d9f40a"
}

### Delete 
POST {{Api_Url}}/Users/Delete 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
 "id": "686c78c5-2cab-4204-8c3e-08dca404950f",
  "isDeleted": true 
}

### All 
//TODO: Get ile de çalışıyor post ile de
GET {{Api_Url}}/Users/All 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

### Me 
//TODO: Get ile de çalışıyor post ile de
GET {{Api_Url}}/Users/Me 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

### Detail
GET {{Api_Url}}/Users/Detail
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id":"dc8f0003-f2e4-495a-b05d-08dca021c461"
}


