@Api_Url = http://localhost:5077

@Jwt_Key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyYmJkNWUxZS1mZTNkLTQ1YzctOWU3Zi1iYTBmMmU3OThlMWUiLCJkZXBhcnRtZW50aWQiOiI3NDlhZGQzNC1kZTY3LWM3NDQtOGQyNi0wYTNlMTg0OTliMzYiLCJnaXZlbl9uYW1lIjoiYWRtaW5AdGFza21hbmFnZW1lbnRzeXN0ZW0uY29tIiwidW5pcXVlX25hbWUiOiJBZG1pbiBVc2VyIiwibmJmIjoxNzQ0OTAxNjE0LCJleHAiOjE3NDUxNjA4MTQsImlhdCI6MTc0NDkwMTYxNCwiYXVkIjoiVG9kb0FwcC5jb20udHIifQ.9QFeJAhH-zfrpmDIQz7THgGTmkOr7mq5dVNLq6oIy8w

### Login
POST {{Api_Url}}/Users/Login
Accept: application/json
Content-Type: application/json

{
  "email":"yahya_eraltay@gmail.com"
}

### Create 
POST {{Api_Url}}/Users/Create 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "email": "yahya_eraltay@gmail.com",
  "firstName": "Yahya",
  "lastName": "Eraltay",
  "departmentId": "06E03437-4EAB-49C8-E3DA-08DD78D3E24F"
}

### Update 
PUT {{Api_Url}}/Users/Update 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "B5ADDA78-A1EF-44CE-D874-08DD78D43DFD",
  "email": "yahya_eraltay@gmail.com",
  "firstName": "Yahya",
  "lastName": "Eraltay",
  "departmentId": "06E03437-4EAB-49C8-E3DA-08DD78D3E24F"
}

### Delete 
DELETE {{Api_Url}}/Users/Delete 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
 "id": "B5ADDA78-A1EF-44CE-D874-08DD78D43DFD",
  "isDeleted": false 
}

### All 
GET {{Api_Url}}/Users/All 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "filters": [],
  "pageRequest": {
    "currentPage": 1,
    "perPageCount": 10,
    "listAll": true
  }
}

### Me 
GET {{Api_Url}}/Users/Me 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

### Detail
GET {{Api_Url}}/Users/Detail
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id":"B5ADDA78-A1EF-44CE-D874-08DD78D43DFD"
}


