@Api_Url = http://localhost:5077

@Jwt_Key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkM2FmYWQxOC0yZTVjLTRjZmYtOTVkNi0wOGRjZGEyYzI5ZWIiLCJnaXZlbl9uYW1lIjoic2Vya2FuX3l1cnRAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJTZXJrYW4gWXVydCIsIm5iZiI6MTcyNjkxNjI0NSwiZXhwIjoxNzI3MTc1NDQ1LCJpYXQiOjE3MjY5MTYyNDUsImF1ZCI6IlRvZG9BcHAuY29tLnRyIn0.2SQzaVZJjbdSNp_Bo9JTElioiqkNhMTFRFM5ZjE4cAM

### Login
POST {{Api_Url}}/Users/Login
Accept: application/json
Content-Type: application/json

{
  "email":"serkan_yurt@gmail.com"
}

### Create 
POST {{Api_Url}}/Users/Create 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "email": "serkan_yurt@gmail.com",
  "firstName": "Serkan",
  "lastName": "Yurt",
  "departmentId": "2ef2c94c-fc70-4c0b-145b-08dcda2beedc"
}

### Update 
PUT {{Api_Url}}/Users/Update 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id": "17399264-cc9f-422a-f343-08dca403efbb",
  "email": "john_doe@gmail.com",
  "firstName": "John",
  "lastName": "Doe",
  "departmentId": "0f4f87cc-db80-4974-bae7-08dca0d9f40a"
}

### Delete 
DELETE {{Api_Url}}/Users/Delete 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
 "id": "f18bf023-f884-4c3f-68b3-08dca49f5a8b",
  "isDeleted": true 
}

### All 
//TODO: Get ile de çalışıyor post ile de
GET {{Api_Url}}/Users/All 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

### Me 
//TODO: Get ile de çalışıyor post ile de
GET {{Api_Url}}/Users/Me 
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

### Detail
GET {{Api_Url}}/Users/Detail
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Jwt_Key}}

{
  "id":"f18bf023-f884-4c3f-68b3-08dca49f5a8b"
}


